### ISSUE TITLE
Color Picker Module

### ISSUE THREAD

**Issue by jonguan** [veereshkamble/CMPE202_ProjectGroup29#15]
Implement color picker module to set color of country

**Comment by madhuribharatula** [comment]
Color Selection Panel implmentation for the edges and nodes graph

**Comment by veereshkamble** [comment]
Combined color palette with a new map. A rough sketch of how  a typical game screen would look like.

**Comment by madhuribharatula** [comment]
Static Color Pallet is done  but need to validate the colors
