### ISSUE TITLE
title screen to switch between maps

### ISSUE THREAD

**Issue by jonguan** [veereshkamble/CMPE202_ProjectGroup29#19]

**Comment by anubhamandal** [comment]
Combined the graphs from Madhuri and Jon.
Please update if others have completed their graphs. 
Once done, we can find an optimised way of reusing the actors from all the graphs in order to minimise the number of actors

**Comment by veereshkamble** [comment]
Added Graph 6 to the main menu. And updated.
But faced problems while integrating my color palette into the main menu.

**Comment by anubhamandal** [comment]
Title screen created and all the graphs are integrated.
**Need to add number of players section in the title page.
