### ISSUE TITLE
Project topic selection

### ISSUE THREAD

**Issue by anubhamandal** [veereshkamble/CMPE202_ProjectGroup29#2]

**Comment by jonguan** [comment]
Activities can be found here: http://csunplugged.org/activities/

**Comment by anubhamandal** [comment]
Project selection voting....

My choices:
1. Finite state automata
2. public key encryption
3. Minimal spanning tree

**Comment by ShilpaChandra266** [comment]
My voting for project topics:
1. Public key encryption
2. Error detection
3. Information Hiding

**Comment by madhuribharatula** [comment]
My List of activities:

1.Minimal Spanning trees
2.Public key encryption/Cryptographic protocols
3.Steiner Trees

**Comment by madhuribharatula** [comment]
Topics listed by our team and their votes:

public key encryption - 5
Graph coloring - 3
Minimal spanning trees - 2 
cryptographic protocols - 2
Finite State Automata -1
Stenier trees -1
error detection -1
information hiding -1
Finite state automata -1
sorting -1
sorting networks -1

**Comment by veereshkamble** [comment]
Activities which interested me:
1. Graph coloring.
2.Public Key Encryption
3.Sorting Networks

**Comment by jonguan** [comment]
1. Cryptographic Protocols
2. Error Detection
3. Routing and Deadlock

**Comment by madhuribharatula** [comment]
Our selected activity is "Graph Coloring"
