### ISSUE TITLE
Update the Burndown Chart in google sheet

### ISSUE THREAD

**Issue by anubhamandal** [veereshkamble/CMPE202_ProjectGroup29#26]
https://docs.google.com/spreadsheets/d/1cmaxxF07YOfKKBRs5cfvSRJJVSr83HqnlXmW_MKGwP4/edit#gid=0

**Comment by anubhamandal** [comment]
Combined the graphs from Madhuri and Jon.
Please update if others have completed their graphs. 
Once done, we can find an optimised way of reusing the actors from all the graphs in order to minimise the number of actors

**Comment by veereshkamble** [comment]
Updated!
