### ISSUE TITLE
Selection of project deliverables

### ISSUE THREAD

**Issue by anubhamandal** [veereshkamble/CMPE202_ProjectGroup29#28]
Select one of the following Project Deliverable to "own" in the Team Project: 
UI Wireframes: Create UI wireframes for each of the screen in your team’s solution 
(this can be done by hand or electronically with a tool like “Pencil”)
An Activity Diagram of the game play showing how multiple players interact with the game and each other.
A Design Sequence Diagram showing the functionality of the Game end-to-end.  (I.E.  From Actors playing the game to Object Interaction in the Client and to API backends on the Cloud).
A Use Case Specification for one of the Use Cases in the Game.  Use the Use Case template presented in class.
A User Story along with the supporting requirements specifications as BDD Scenarios.  Make sure to use the User Voice format discussed in class and identity at least five scenarios (one for "happy path" and additonal "error" scenarios).

**Comment by madhuribharatula** [comment]
For this week I will draw UI WireFrame for the Graph -3

**Comment by ShilpaChandra266** [comment]
For this week i did activity diagram for single player game

**Comment by anubhamandal** [comment]
Anubha - Class Diagram
Shilpa - UI Wireframe
Madhuri - Use Case
Jon - Activity Diagram
Veeresh - Sequence 
Kelly - User story
