### ISSUE TITLE
Sketch and Storyboarding

### ISSUE THREAD

**Issue by jonguan** [veereshkamble/CMPE202_ProjectGroup29#6]

**Comment by anubhamandal** [comment]
![p_20160925_104508_1](https://cloud.githubusercontent.com/assets/21416362/18817235/b5139ff8-8310-11e6-80b0-8bbca6f3f003.jpg)

Basic idea of forming the map as discussed in the meeting.

**Comment by ShilpaChandra266** [comment]
[Graph Coloring(SHILPA CHANDRA).docx](https://github.com/veereshkamble/CMPE202_ProjectGroup29/files/491833/Graph.Coloring.SHILPA.CHANDRA.docx)

**Comment by veereshkamble** [comment]
Selecting the topic - Graph Coloring Problem
[Graph Coloring - Veeresh Kamble.docx](https://github.com/veereshkamble/CMPE202_ProjectGroup29/files/491937/Graph.Coloring.-.Veeresh.Kamble.docx)

**Comment by madhuribharatula** [comment]
[graphColoring_sketch_basic.pdf](https://github.com/veereshkamble/CMPE202_ProjectGroup29/files/491954/graphColoring_sketch_basic.pdf)

**Comment by kelalvarez** [comment]
[graphColoring-KAA.pdf](https://github.com/veereshkamble/CMPE202_ProjectGroup29/files/492117/graphColoring-KAA.pdf)
