### ISSUE TITLE
Deliverable: Extra Credit video

### ISSUE THREAD

**Issue by jonguan** [veereshkamble/CMPE202_ProjectGroup29#70]
Select a Elementary/Middle or High School Class near SJSU and host a CS Unplugged Activity. 
Team will need to contact the School/Teacher to coordinate place and time for the CS Activity and Game Demo. 
Plan for about 4 hours.
Alternatively, Identify at least 5 students on Campus who are not CS or CMPE majors. 
Host a CS Unplugged session with the Activity and Game your team selected. 
Plan for about 2 hours.
Extra Credit Session must be recorded.  The entire session need not be published for the submission.  Create a 15 minutes "highlights" Video.  Note:  Team must make sure to get permissions from participants that they are okay with being video recorded.

**Comment by anubhamandal** [comment]
2parts video:
- Explanation: can give examples of Sudoku game, and real time implementation as time table/ exam schedule
- Activity by the other students, playing the game

**Comment by anubhamandal** [comment]
Video shot done, need to edit
